// <auto-generated />
using System;
using Erp_Api.Models.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Erp_Api.Migrations
{
    [DbContext(typeof(ErpBdContext))]
    [Migration("20260126131937_des")]
    partial class des
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("erp")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Adresse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("adr_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodePostal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("adr_code_postal");

                    b.Property<int?>("EmployeId")
                        .HasColumnType("integer");

                    b.Property<int?>("EntrepriseId")
                        .HasColumnType("integer");

                    b.Property<string>("Pays")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("adr_pays");

                    b.Property<string>("Rue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("adr_rue");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("adr_ville");

                    b.HasKey("Id");

                    b.HasIndex("EmployeId")
                        .IsUnique();

                    b.HasIndex("EntrepriseId")
                        .IsUnique();

                    b.ToTable("t_e_adresse_adr", "erp");
                });

            modelBuilder.Entity("Erp_Api.Models.Entity.Tables.Entitees.Candidature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("can_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCandidature")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("can_date_candidature");

                    b.Property<DateTime?>("DateNaissance")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("can_date_naissance");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("can_email");

                    b.Property<int?>("EmployeId")
                        .HasColumnType("integer")
                        .HasColumnName("can_employe_id");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("can_nom");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("can_notes");

                    b.Property<int>("OffreEmploiId")
                        .HasColumnType("integer")
                        .HasColumnName("can_offre_emploi_id");

                    b.Property<int?>("PlateformeId")
                        .HasColumnType("integer")
                        .HasColumnName("can_plateforme_id");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("can_prenom");

                    b.Property<decimal?>("PretentionsSalariales")
                        .HasColumnType("numeric")
                        .HasColumnName("can_pretentions_salariales");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("can_status_id");

                    b.Property<string>("Telephone")
                        .HasColumnType("text")
                        .HasColumnName("can_telephone");

                    b.HasKey("Id");

                    b.HasIndex("EmployeId");

                    b.HasIndex("OffreEmploiId");

                    b.HasIndex("PlateformeId");

                    b.ToTable("t_e_candidature_can", "erp");
                });

            modelBuilder.Entity("Erp_Api.Models.Entity.Tables.Entitees.Employe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("emp_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("emp_datenaissance");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("emp_email");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("emp_login");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("emp_nom");

                    b.Property<string>("NumSecuriteSociale")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("emp_numsecuritesociale");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("emp_password_hash");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("emp_prenom");

                    b.Property<string>("Telephone")
                        .HasColumnType("text")
                        .HasColumnName("emp_telephone");

                    b.HasKey("Id");

                    b.ToTable("t_e_employe_emp", "erp");
                });

            modelBuilder.Entity("Erp_Api.Models.Entity.Tables.Entitees.Entite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ent_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("EstEntreprise")
                        .HasColumnType("boolean")
                        .HasColumnName("ent_est_entreprise");

                    b.Property<bool>("EstSilsefNapa")
                        .HasColumnType("boolean")
                        .HasColumnName("ent_est_silsefnapa");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ent_nom");

                    b.Property<string>("Siret")
                        .HasColumnType("text")
                        .HasColumnName("ent_siret");

                    b.Property<string>("Telephone")
                        .HasColumnType("text")
                        .HasColumnName("ent_telephone");

                    b.HasKey("Id");

                    b.ToTable("t_e_entite_ent", "erp");
                });

            modelBuilder.Entity("Erp_Api.Models.Entity.Tables.Entitees.Entretien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ent_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidatureId")
                        .HasColumnType("integer")
                        .HasColumnName("ent_candidature_id");

                    b.Property<DateTime>("DateEntretien")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("ent_date");

                    b.Property<int?>("InterviewerId")
                        .HasColumnType("integer")
                        .HasColumnName("ent_interviewer_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("ent_notes");

                    b.Property<int>("TypeEntretien")
                        .HasColumnType("integer");

                    b.Property<int>("TypeEntretienId")
                        .HasColumnType("integer")
                        .HasColumnName("ent_type_entretien_id");

                    b.HasKey("Id");

                    b.HasIndex("CandidatureId");

                    b.HasIndex("InterviewerId");

                    b.ToTable("t_e_entretien_ent", "erp");
                });

            modelBuilder.Entity("Erp_Api.Models.Entity.Tables.Entitees.FeuilleTemps", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ft_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Commentaire")
                        .HasColumnType("text")
                        .HasColumnName("ft_commentaire");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("ft_date");

                    b.Property<int>("EmployeId")
                        .HasColumnType("integer")
                        .HasColumnName("ft_employe_id");

                    b.Property<bool>("EstMatin")
                        .HasColumnType("boolean")
                        .HasColumnName("ft_est_matin");

                    b.Property<int?>("ProjetId")
                        .HasColumnType("integer")
                        .HasColumnName("ft_projet_id");

                    b.HasKey("Id");

                    b.HasIndex("EmployeId");

                    b.HasIndex("ProjetId");

                    b.ToTable("t_e_feuilletemps_ft", "erp");
                });

            modelBuilder.Entity("Erp_Api.Models.Entity.Tables.Entitees.Materiel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("mat_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mat_nom");

                    b.Property<int?>("ProjetId")
                        .HasColumnType("integer")
                        .HasColumnName("mat_projet_id");

                    b.Property<int>("Quantite")
                        .HasColumnType("integer")
                        .HasColumnName("mat_quantite");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("mat_type");

                    b.HasKey("Id");

                    b.HasIndex("ProjetId");

                    b.ToTable("t_e_materiel_mat", "erp");
                });

            modelBuilder.Entity("Erp_Api.Models.Entity.Tables.Entitees.Offre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("off_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateCloture")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("off_date_cloture");

                    b.Property<DateTime>("DatePublication")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("off_date_publication");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("off_description");

                    b.Property<int?>("EntiteId")
                        .HasColumnType("integer");

                    b.Property<int?>("EntrepriseId")
                        .HasColumnType("integer")
                        .HasColumnName("off_entite_id");

                    b.Property<bool>("EstActive")
                        .HasColumnType("boolean")
                        .HasColumnName("off_est_active");

                    b.Property<int>("NombrePostes")
                        .HasColumnType("integer")
                        .HasColumnName("off_nombre_postes");

                    b.Property<decimal?>("SalaireMax")
                        .HasColumnType("numeric")
                        .HasColumnName("off_salaire_max");

                    b.Property<decimal?>("SalaireMin")
                        .HasColumnType("numeric")
                        .HasColumnName("off_salaire_min");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("off_titre");

                    b.Property<int>("TypeContrat")
                        .HasColumnType("integer")
                        .HasColumnName("off_type_contrat_id");

                    b.HasKey("Id");

                    b.HasIndex("EntiteId");

                    b.ToTable("t_e_offre_off", "erp");
                });

            modelBuilder.Entity("Erp_Api.Models.Entity.Tables.Entitees.Plateforme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tco_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pla_libelle");

                    b.HasKey("Id");

                    b.ToTable("t_e_plateforme_pla", "erp");
                });

            modelBuilder.Entity("Erp_Api.Models.Entity.Tables.Entitees.Projet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pro_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("pro_date_debut");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("pro_date_fin");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("pro_description");

                    b.Property<int?>("EmployeResponsableId")
                        .HasColumnType("integer")
                        .HasColumnName("pro_employeresponsable_id");

                    b.Property<int?>("EntiteClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("pro_entitecliente_id");

                    b.Property<int?>("EntiteRealisatriceId")
                        .HasColumnType("integer")
                        .HasColumnName("pro_entiterealisatrice_id");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pro_nom");

                    b.Property<int>("Priorite")
                        .HasColumnType("integer")
                        .HasColumnName("pro_priorite");

                    b.Property<int?>("TypeProjetId")
                        .HasColumnType("integer")
                        .HasColumnName("pro_typeprojet_id");

                    b.HasKey("Id");

                    b.HasIndex("EmployeResponsableId");

                    b.HasIndex("EntiteClienteId");

                    b.HasIndex("EntiteRealisatriceId");

                    b.HasIndex("TypeProjetId");

                    b.ToTable("t_e_projet_pro", "erp");
                });

            modelBuilder.Entity("Erp_Api.Models.Entity.Tables.Entitees.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("rol_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rol_nom");

                    b.HasKey("Id");

                    b.ToTable("t_e_role_rol", "erp");
                });

            modelBuilder.Entity("Erp_Api.Models.Entity.Tables.Entitees.Tache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tac_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("tac_datedebut");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("tac_datefin");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("tac_Description");

                    b.Property<int?>("EmployeAssigneId")
                        .HasColumnType("integer")
                        .HasColumnName("tac_employe_assigne_id");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tac_nom");

                    b.Property<int>("Priorite")
                        .HasColumnType("integer")
                        .HasColumnName("tac_priorite");

                    b.Property<int?>("ProjetId")
                        .HasColumnType("integer")
                        .HasColumnName("tac_projet_id");

                    b.Property<int>("Statut")
                        .HasColumnType("integer")
                        .HasColumnName("tac_statut");

                    b.Property<int?>("TacheParenteId")
                        .HasColumnType("integer")
                        .HasColumnName("tac_tache_parente_id");

                    b.HasKey("Id");

                    b.HasIndex("EmployeAssigneId");

                    b.HasIndex("ProjetId");

                    b.HasIndex("TacheParenteId");

                    b.ToTable("t_e_tache_tac", "erp");
                });

            modelBuilder.Entity("Erp_Api.Models.Entity.Tables.Entitees.TypeProjet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tpo_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tpo_nom");

                    b.HasKey("Id");

                    b.ToTable("t_e_typeprojet_tpo", "erp");
                });

            modelBuilder.Entity("Erp_Api.Models.Entity.Tables.Jointures.A_Pour_Role", b =>
                {
                    b.Property<int>("EmployeId")
                        .HasColumnType("integer")
                        .HasColumnName("apr_employe_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("apr_role_id");

                    b.HasKey("EmployeId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("t_j_a_pour_role_apr", "erp");
                });

            modelBuilder.Entity("Erp_Api.Models.Entity.Tables.Jointures.EmployeEntite", b =>
                {
                    b.Property<int>("EmployeId")
                        .HasColumnType("integer")
                        .HasColumnName("eem_employe_id");

                    b.Property<int>("EntiteId")
                        .HasColumnType("integer")
                        .HasColumnName("eem_entite_id");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("eem_date_debut");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("eem_date_fin");

                    b.Property<string>("Poste")
                        .HasColumnType("text")
                        .HasColumnName("eem_poste");

                    b.HasKey("EmployeId", "EntiteId");

                    b.HasIndex("EntiteId");

                    b.ToTable("t_j_employe_entite_eem", "erp");
                });

            modelBuilder.Entity("Adresse", b =>
                {
                    b.HasOne("Erp_Api.Models.Entity.Tables.Entitees.Employe", "Employe")
                        .WithOne("Adresse")
                        .HasForeignKey("Adresse", "EmployeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Erp_Api.Models.Entity.Tables.Entitees.Entite", "Entite")
                        .WithOne("Adresse")
                        .HasForeignKey("Adresse", "EntrepriseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Employe");

                    b.Navigation("Entite");
                });

            modelBuilder.Entity("Erp_Api.Models.Entity.Tables.Entitees.Candidature", b =>
                {
                    b.HasOne("Erp_Api.Models.Entity.Tables.Entitees.Employe", "Employe")
                        .WithMany()
                        .HasForeignKey("EmployeId");

                    b.HasOne("Erp_Api.Models.Entity.Tables.Entitees.Offre", "Offre")
                        .WithMany("Candidatures")
                        .HasForeignKey("OffreEmploiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Erp_Api.Models.Entity.Tables.Entitees.Plateforme", "Plateforme")
                        .WithMany("Candidature")
                        .HasForeignKey("PlateformeId");

                    b.Navigation("Employe");

                    b.Navigation("Offre");

                    b.Navigation("Plateforme");
                });

            modelBuilder.Entity("Erp_Api.Models.Entity.Tables.Entitees.Entretien", b =>
                {
                    b.HasOne("Erp_Api.Models.Entity.Tables.Entitees.Candidature", "Candidature")
                        .WithMany()
                        .HasForeignKey("CandidatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Erp_Api.Models.Entity.Tables.Entitees.Employe", "Interviewer")
                        .WithMany()
                        .HasForeignKey("InterviewerId");

                    b.Navigation("Candidature");

                    b.Navigation("Interviewer");
                });

            modelBuilder.Entity("Erp_Api.Models.Entity.Tables.Entitees.FeuilleTemps", b =>
                {
                    b.HasOne("Erp_Api.Models.Entity.Tables.Entitees.Employe", "Employe")
                        .WithMany()
                        .HasForeignKey("EmployeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Erp_Api.Models.Entity.Tables.Entitees.Projet", "Projet")
                        .WithMany()
                        .HasForeignKey("ProjetId");

                    b.Navigation("Employe");

                    b.Navigation("Projet");
                });

            modelBuilder.Entity("Erp_Api.Models.Entity.Tables.Entitees.Materiel", b =>
                {
                    b.HasOne("Erp_Api.Models.Entity.Tables.Entitees.Projet", "Projet")
                        .WithMany()
                        .HasForeignKey("ProjetId");

                    b.Navigation("Projet");
                });

            modelBuilder.Entity("Erp_Api.Models.Entity.Tables.Entitees.Offre", b =>
                {
                    b.HasOne("Erp_Api.Models.Entity.Tables.Entitees.Entite", "Entite")
                        .WithMany()
                        .HasForeignKey("EntiteId");

                    b.Navigation("Entite");
                });

            modelBuilder.Entity("Erp_Api.Models.Entity.Tables.Entitees.Projet", b =>
                {
                    b.HasOne("Erp_Api.Models.Entity.Tables.Entitees.Employe", "EmployeResponsable")
                        .WithMany("ProjetsResponsable")
                        .HasForeignKey("EmployeResponsableId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Erp_Api.Models.Entity.Tables.Entitees.Entite", "EntiteCliente")
                        .WithMany("ProjetsCommandes")
                        .HasForeignKey("EntiteClienteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Erp_Api.Models.Entity.Tables.Entitees.Entite", "EntiteRealisatrice")
                        .WithMany("ProjetsRealises")
                        .HasForeignKey("EntiteRealisatriceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Erp_Api.Models.Entity.Tables.Entitees.TypeProjet", "TypeProjet")
                        .WithMany("Projets")
                        .HasForeignKey("TypeProjetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("EmployeResponsable");

                    b.Navigation("EntiteCliente");

                    b.Navigation("EntiteRealisatrice");

                    b.Navigation("TypeProjet");
                });

            modelBuilder.Entity("Erp_Api.Models.Entity.Tables.Entitees.Tache", b =>
                {
                    b.HasOne("Erp_Api.Models.Entity.Tables.Entitees.Employe", "EmployeAssigne")
                        .WithMany("TachesAssignees")
                        .HasForeignKey("EmployeAssigneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Erp_Api.Models.Entity.Tables.Entitees.Projet", "Projet")
                        .WithMany("Taches")
                        .HasForeignKey("ProjetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Erp_Api.Models.Entity.Tables.Entitees.Tache", "TacheParente")
                        .WithMany("SousTaches")
                        .HasForeignKey("TacheParenteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EmployeAssigne");

                    b.Navigation("Projet");

                    b.Navigation("TacheParente");
                });

            modelBuilder.Entity("Erp_Api.Models.Entity.Tables.Jointures.A_Pour_Role", b =>
                {
                    b.HasOne("Erp_Api.Models.Entity.Tables.Entitees.Employe", "Employe")
                        .WithMany("Employeroles")
                        .HasForeignKey("EmployeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Erp_Api.Models.Entity.Tables.Entitees.Role", "Role")
                        .WithMany("EmployeRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employe");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Erp_Api.Models.Entity.Tables.Jointures.EmployeEntite", b =>
                {
                    b.HasOne("Erp_Api.Models.Entity.Tables.Entitees.Employe", "Employe")
                        .WithMany("EmployeEntites")
                        .HasForeignKey("EmployeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Erp_Api.Models.Entity.Tables.Entitees.Entite", "Entite")
                        .WithMany("EmployeEntites")
                        .HasForeignKey("EntiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employe");

                    b.Navigation("Entite");
                });

            modelBuilder.Entity("Erp_Api.Models.Entity.Tables.Entitees.Employe", b =>
                {
                    b.Navigation("Adresse");

                    b.Navigation("EmployeEntites");

                    b.Navigation("Employeroles");

                    b.Navigation("ProjetsResponsable");

                    b.Navigation("TachesAssignees");
                });

            modelBuilder.Entity("Erp_Api.Models.Entity.Tables.Entitees.Entite", b =>
                {
                    b.Navigation("Adresse");

                    b.Navigation("EmployeEntites");

                    b.Navigation("ProjetsCommandes");

                    b.Navigation("ProjetsRealises");
                });

            modelBuilder.Entity("Erp_Api.Models.Entity.Tables.Entitees.Offre", b =>
                {
                    b.Navigation("Candidatures");
                });

            modelBuilder.Entity("Erp_Api.Models.Entity.Tables.Entitees.Plateforme", b =>
                {
                    b.Navigation("Candidature");
                });

            modelBuilder.Entity("Erp_Api.Models.Entity.Tables.Entitees.Projet", b =>
                {
                    b.Navigation("Taches");
                });

            modelBuilder.Entity("Erp_Api.Models.Entity.Tables.Entitees.Role", b =>
                {
                    b.Navigation("EmployeRoles");
                });

            modelBuilder.Entity("Erp_Api.Models.Entity.Tables.Entitees.Tache", b =>
                {
                    b.Navigation("SousTaches");
                });

            modelBuilder.Entity("Erp_Api.Models.Entity.Tables.Entitees.TypeProjet", b =>
                {
                    b.Navigation("Projets");
                });
#pragma warning restore 612, 618
        }
    }
}
