// <auto-generated />
using System;
using Erp_Api.Models.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Erp_Api.Migrations
{
    [DbContext(typeof(ErpBdContext))]
    [Migration("20260120112233_correctionloginmapped")]
    partial class correctionloginmapped
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("erp")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Adresse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("adr_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodePostal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("adr_code_postal");

                    b.Property<int?>("EmployeId")
                        .HasColumnType("integer");

                    b.Property<int?>("EntrepriseId")
                        .HasColumnType("integer");

                    b.Property<string>("Pays")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("adr_pays");

                    b.Property<string>("Rue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("adr_rue");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("adr_ville");

                    b.HasKey("Id");

                    b.HasIndex("EmployeId")
                        .IsUnique();

                    b.HasIndex("EntrepriseId")
                        .IsUnique();

                    b.ToTable("t_e_adresse_adr", "erp");
                });

            modelBuilder.Entity("Erp_Api.Models.Entity.Tables.Entitees.Employe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("emp_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("emp_datenaissance");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("emp_email");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("emp_login");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("emp_nom");

                    b.Property<string>("NumSecuriteSociale")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("emp_numsecuritesociale");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("emp_password_hash");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("emp_prenom");

                    b.Property<string>("Telephone")
                        .HasColumnType("text")
                        .HasColumnName("emp_telephone");

                    b.HasKey("Id");

                    b.ToTable("t_e_employe_emp", "erp");
                });

            modelBuilder.Entity("Erp_Api.Models.Entity.Tables.Entitees.Entreprise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ent_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ent_nom");

                    b.Property<string>("Telephone")
                        .HasColumnType("text")
                        .HasColumnName("ent_telephone");

                    b.HasKey("Id");

                    b.ToTable("t_e_entreprise_ent", "erp");
                });

            modelBuilder.Entity("Erp_Api.Models.Entity.Tables.Entitees.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("rol_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rol_nom");

                    b.HasKey("Id");

                    b.ToTable("t_e_role_rol", "erp");
                });

            modelBuilder.Entity("Erp_Api.Models.Entity.Tables.Jointures.A_Pour_Role", b =>
                {
                    b.Property<int>("EmployeId")
                        .HasColumnType("integer")
                        .HasColumnName("apr_employe_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("apr_role_id");

                    b.HasKey("EmployeId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("t_j_a_pour_role_apr", "erp");
                });

            modelBuilder.Entity("Erp_Api.Models.Entity.Tables.Jointures.EmployeEntreprise", b =>
                {
                    b.Property<int>("EmployeId")
                        .HasColumnType("integer")
                        .HasColumnName("eem_employe_id");

                    b.Property<int>("EntrepriseId")
                        .HasColumnType("integer")
                        .HasColumnName("eem_entreprise_id");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("eem_date_debut");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("eem_date_fin");

                    b.Property<string>("Poste")
                        .HasColumnType("text")
                        .HasColumnName("eem_poste");

                    b.HasKey("EmployeId", "EntrepriseId");

                    b.HasIndex("EntrepriseId");

                    b.ToTable("t_j_employe_entreprise_eem", "erp");
                });

            modelBuilder.Entity("Adresse", b =>
                {
                    b.HasOne("Erp_Api.Models.Entity.Tables.Entitees.Employe", "Employe")
                        .WithOne("Adresse")
                        .HasForeignKey("Adresse", "EmployeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Erp_Api.Models.Entity.Tables.Entitees.Entreprise", "Entreprise")
                        .WithOne("Adresse")
                        .HasForeignKey("Adresse", "EntrepriseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Employe");

                    b.Navigation("Entreprise");
                });

            modelBuilder.Entity("Erp_Api.Models.Entity.Tables.Jointures.A_Pour_Role", b =>
                {
                    b.HasOne("Erp_Api.Models.Entity.Tables.Entitees.Employe", "Employe")
                        .WithMany("Employeroles")
                        .HasForeignKey("EmployeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Erp_Api.Models.Entity.Tables.Entitees.Role", "Role")
                        .WithMany("EmployeRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employe");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Erp_Api.Models.Entity.Tables.Jointures.EmployeEntreprise", b =>
                {
                    b.HasOne("Erp_Api.Models.Entity.Tables.Entitees.Employe", "Employe")
                        .WithMany("EmployeEntreprises")
                        .HasForeignKey("EmployeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Erp_Api.Models.Entity.Tables.Entitees.Entreprise", "Entreprise")
                        .WithMany("EmployeEntreprises")
                        .HasForeignKey("EntrepriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employe");

                    b.Navigation("Entreprise");
                });

            modelBuilder.Entity("Erp_Api.Models.Entity.Tables.Entitees.Employe", b =>
                {
                    b.Navigation("Adresse");

                    b.Navigation("EmployeEntreprises");

                    b.Navigation("Employeroles");
                });

            modelBuilder.Entity("Erp_Api.Models.Entity.Tables.Entitees.Entreprise", b =>
                {
                    b.Navigation("Adresse");

                    b.Navigation("EmployeEntreprises");
                });

            modelBuilder.Entity("Erp_Api.Models.Entity.Tables.Entitees.Role", b =>
                {
                    b.Navigation("EmployeRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
